module.exports = {
  space: true,
  semicolon: true,
  prettier: 'compat',
  react: true,
  ignores: [
    '.next/**',
    'node_modules/**',
    'dist/**',
    'coverage/**',
    'src/hooks/use-callback-ref.tsx'
  ],
  rules: {
    'react/react-in-jsx-scope': 'off',
    'react/jsx-uses-react': 'off',
    'react-hooks/set-state-in-effect': 'off',
    'no-warning-comments': 'off',
    'import-x/extensions': 'off',
    'import-x/order': 'off',
    '@typescript-eslint/naming-convention': 'off',
    '@typescript-eslint/no-restricted-types': 'off',
    '@typescript-eslint/no-unsafe-type-assertion': 'off',
    '@typescript-eslint/no-unsafe-assignment': 'off',
    '@typescript-eslint/no-unsafe-return': 'off',
    '@typescript-eslint/no-unsafe-member-access': 'off',
    '@typescript-eslint/no-unsafe-call': 'off',
    '@typescript-eslint/no-unsafe-argument': 'off',
    '@typescript-eslint/no-empty-function': 'off',
    '@typescript-eslint/prefer-nullish-coalescing': 'off',
    '@typescript-eslint/consistent-type-definitions': 'off',
    '@typescript-eslint/no-confusing-void-expression': 'off',
    '@typescript-eslint/strict-void-return': 'off',
    '@stylistic/max-len': 'off',
    'max-lines': 'off',
    'max-depth': 'off',
    'max-nested-callbacks': 'off',
    'complexity': 'off',
    'unicorn/prevent-abbreviations': 'off',
    'unicorn/no-nested-ternary': 'off',
    'unicorn/no-negated-condition': 'off',
    'unicorn/filename-case': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/no-array-sort': 'off',
    'unicorn/prefer-set-has': 'off',
    'unicorn/prefer-includes': 'off',
    'unicorn/prefer-spread': 'off',
    'unicorn/no-array-reduce': 'off',
    'unicorn/no-array-callback-reference': 'off',
    'no-negated-condition': 'off',
    'react/boolean-prop-naming': 'off',
    'react-hooks/exhaustive-deps': 'off',
    'react-hooks/incompatible-library': 'off',
    'react-hooks/preserve-manual-memoization': 'off',
    'react-hooks/purity': 'off',
    'react-hooks/refs': 'off',
    'react/prop-types': 'off',
    'react/no-array-index-key': 'off',
    'react/function-component-definition': 'off',
    'react/no-object-type-as-default-prop': 'off',
    'react/no-danger': 'off',
    'react/no-unknown-property': 'off',
    'react/no-unescaped-entities': 'off',
    'react/no-unused-prop-types': 'off',
    'react/jsx-no-target-blank': 'off',
    'preserve-caught-error': 'off',
    'no-alert': 'off',
    'no-promise-executor-return': 'off',
    'no-lone-blocks': 'off',
    'eqeqeq': 'off',
    'new-cap': 'off',
    'radix': 'off',
    'no-return-assign': 'off',
    'no-unsafe-optional-chaining': 'off',
    'prefer-destructuring': 'off',
    'logical-assignment-operators': 'off',
    'n/prefer-global/process': 'off',
    '@typescript-eslint/switch-exhaustiveness-check': 'off',
    '@typescript-eslint/no-deprecated': 'off',
    '@typescript-eslint/no-empty-object-type': 'off',
    '@typescript-eslint/no-redeclare': 'off',
    '@typescript-eslint/restrict-template-expressions': 'off',
    '@typescript-eslint/no-unused-expressions': 'off',
    '@typescript-eslint/promise-function-async': 'off',
    '@typescript-eslint/use-unknown-in-catch-callback-variable': 'off',
    '@typescript-eslint/prefer-optional-chain': 'off',
    '@typescript-eslint/consistent-type-assertions': 'off',
    '@stylistic/padding-line-between-statements': 'off',
    'unicorn/explicit-length-check': 'off',
    'unicorn/prefer-logical-operator-over-ternary': 'off',
    'unicorn/prefer-array-some': 'off',
    'capitalized-comments': 'off',
    'require-unicode-regexp': 'off'
  }
};
